<?php

namespace PbbgIo\Titan\Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use PbbgIo\Titan\Tests\TestCase;
use PbbgIo\Titan\Tests\User;

class HomepageTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testShouldRedirectToLoginIfUnauthenticated()
    {
        $req = $this->get('/')
            ->assertRedirect('/game');

    }

    public function testShouldNotRedirectIfAuthenticated()
    {
        $user = User::create([
            'name'  =>  'test',
            'email' =>  'test@asdg.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => \Str::random(10),
        ]);

        $this->actingAs($user)
            ->get('/')
            ->assertRedirect('/game');
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
